apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
spec:
  selector:
    matchLabels:
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        tier: backend
    spec:
      volumes:
      - name: efs-volume
        persistentVolumeClaim:
          claimName: efs-pvc
      containers:
      - name: back-app
        image: suhwan11/backend:testv1
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: efs-volume
          mountPath: /data
        resources:
          requests:
            cpu: 200m
            memory: 200M
        livenessProbe:
          httpGet:
            ports: 8080
            path: /
        startupProbe:
          httpGet:
            ports: 8080
            path: /
        readinessProbe:
          httpGet:
            ports: 8080
            path: /


