apiVersion: v1
kind: Service
metadata:
  name: back-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/services"
spec:
  selector:
    tier: backend
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31111
  type: NodePort
