apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31112
  - port: 443
    targetPort: 80
    nodePort: 31113
  selector: 
    tier: frontend
